### ISSUE TITLE
Add WinUI/Uno support

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [SKProCH/Material.Icons#26]
I dont know how to make a pull request. I alredy done. Project is atached 

[Material.Icons.zip](https://github.com/SKProCH/Material.Icons/files/13379528/Material.Icons.zip)

**Comment by SKProCH** [comment]
I'll take a look at the weekend.

**Comment by SKProCH** [comment]
Imported project in `uno_winui` branch. Spend a 2 hours trying to compile it with no success.
Errors:
```
5>Material.Icons.UNO.csproj: Error NU1012 : Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-maccatalyst, net8.0-android, net8.0-ios
5>Microsoft.NET.TargetFrameworkInference.targets(121,5): Error NETSDK1208 : The target platform identifier ios was not recognized. This is because MSBuildEnableWorkloadResolver is set to false which disables .NET SDK Workloads which is required for this identifer. Unset this environment variable or MSBuild property to enable workloads.
5>Microsoft.NET.TargetFrameworkInference.targets(121,5): Error NETSDK1208 : The target platform identifier android was not recognized. This is because MSBuildEnableWorkloadResolver is set to false which disables .NET SDK Workloads which is required for this identifer. Unset this environment variable or MSBuild property to enable workloads.
5>Material.Icons.UNO.csproj: Error NU1012 : Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-maccatalyst, net8.0-android, net8.0-ios
5>Microsoft.NET.TargetFrameworkInference.targets(121,5): Error NETSDK1208 : The target platform identifier maccatalyst was not recognized. This is because MSBuildEnableWorkloadResolver is set to false which disables .NET SDK Workloads which is required for this identifer. Unset this environment variable or MSBuild property to enable workloads.
```
Workloads:
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    34.0.43/8.0.100        SDK 8.0.100        
ios                        17.0.8478/8.0.100      SDK 8.0.100        
maui                       8.0.3/8.0.100          SDK 8.0.100        
maui-android               8.0.3/8.0.100          SDK 8.0.100        
maui-ios                   8.0.3/8.0.100          SDK 8.0.100
```
This is also the reason because i dont like uno and anything related.  
Also, i think what library doesn't need to target all the `net8.0;net8.0-ios;net7.0-maccatalyst;net8.0-android` (but may be i wrong here), just netstandard or netX.0 or somthing.

If you manage to make it works property - send an instruction here, please.

**Comment by cesarchefinho** [comment]
you need to install and run uno-check from command prompt

dotnet tool install --global Uno.Check --version 1.17.0

exit prompt

open promot again winth elevated privileges

uno-check --pre

it will install all componetnts, workloads, android adk, and whatever you need to compile uno in visual studio 2022

**Comment by SKProCH** [comment]
Hmm, i'll try. How this should work inside of CI workflow?

**Comment by SKProCH** [comment]
I've run an Uno.Check and actually nothing is changed.

Here is the log: https://gist.github.com/SKProCH/b516c7c75a255b8137bd551f0e6c2311
Also, `! There were one or more problems detected.`, but i can't see any problems in the unocheck output.

Also, i don't have any Visual Studio installed and using Rider. But actually same build errors appears on just `dotnet build` command, so there is not problem with Rider.

Do you have any suggestions?

**Comment by SKProCH** [comment]
Still no luck to build the library project on linux too.

```
/usr/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.ios.Sdk.net8 [/common/RiderProjects/Material.Icons/Material.Icons.UNO/Material.Icons.UNO.csproj::TargetFramework=net8.0-ios]
/usr/share/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK. [/common/RiderProjects/Material.Icons/Material.Icons.UNO/Material.Icons.UNO.csproj::TargetFramework=net8.0-ios]
```

Running unocheck also dont help/

**Comment by cesarchefinho** [comment]
Sorry, i never used rider with uno but it works and also with visual studio code. 

there are an rider plugin for uno, you need to install it and also you need to install winappsdk 1.4 that ia required to buid winui3 applicatios (uno is winui3 for mutiplataform, but in windows it relies of winappsdk that comes with vs but not with rider)_

**Comment by cesarchefinho** [comment]
Last thing, On linux you need to use visual studio code or rider to compile uno apps.

**Comment by SKProCH** [comment]
To be honest i still doesn't get what i need to do to just build the library. 

I don't actually need to work with uno projects inside the IDE. I want at least just compile it with `dotnet build` from the command line. But now i can't do it nether on windows or linux. 

This info required to create a CI script which can build the nupkg file to publish it to nuget.org.

**Comment by cesarchefinho** [comment]
I will try to make an project that compile with CLand send to you.

If  I cant get it working with CL I wil try an WinUi3 only project without uno that compile with CL

Thanks

**Comment by SKProCH** [comment]
Not CLand, actually. By CI a mean Continuous Integration - GitHub Actions in this case. 

Current pipeline to publish a packages to nuget listed here - https://github.com/SKProCH/Material.Icons/blob/master/.github/workflows/publish.yml

I need a script which results to creating a nuget package to publish it to nuget.org.  
So, currently i can't figure out how to do it, since `dotnet build` refuses to work for me in uno projects.

**Comment by CastelloBrancoTecnologia** [comment]
I made an simplification and target only winui net7.

I will work on UNO Version in nexts weeks if WinUI is OK

Can you test this project if it will integrate with your GitHub CL ?

Thanks

[Material.Icons.WinUI.zip](https://github.com/SKProCH/Material.Icons/files/13404805/Material.Icons.WinUI.zip)

**Comment by CastelloBrancoTecnologia** [comment]
I maded an simplified version that only target to WinUI

Can you check if it works with your GitHubCL ?

If yes then in next weeks i will work with uno version and try again send to you, ok ?

thanks

And sorry to my mistakes with uno i will find the solution to it

[Material.Icons.WinUI.zip](https://github.com/SKProCH/Material.Icons/files/13404842/Material.Icons.WinUI.zip)

**Comment by cesarchefinho** [comment]
> To be honest i still doesn't get what i need to do to just build the library.
> 
> I don't actually need to work with uno projects inside the IDE. I want at least just compile it with `dotnet build` from the command line. But now i can't do it nether on windows or linux.
> 
> This info required to create a CI script which can build the nupkg file to publish it to nuget.org.

can you use

msbuild <project>.csproj -t:<projecttobuild> ? or something lime this

also see my winui project please

thanks

**Comment by SKProCH** [comment]
Still can't manage it to run. I've replaced uno projects with winui projects in this commit https://github.com/SKProCH/Material.Icons/commit/8ce468203e6a1c77b26e33d9ac4788d76bf44fb8

In [next commit](https://github.com/SKProCH/Material.Icons/commit/65e3ae56fe9274a0a3af2691a32f498e9b40443f) I've setup the [pipeline file](https://github.com/SKProCH/Material.Icons/actions/runs/6984210757/workflow) (it actually calls the `dotnet build Material.Icons.WinUI -c Release`) to see if there's something wrong with the environment on my machine.

But no, all the builds failed.

- Here is .net 8 build log: https://github.com/SKProCH/Material.Icons/actions/runs/6984210757/job/19006636637
- Here is .net 7 build log: https://github.com/SKProCH/Material.Icons/actions/runs/6984238541/job/19006711147

Guys, I really don't have time to figure out why a simple project on WinUI and Uno can't just build. I find all these Microsoft attempts at UI frameworks (after WPF) cursed and don't see how it can be used, at least because their toolchain just doesn't work.

If you figure it out, and can fix the bugs so that you end up with a .nupkg file that I can upload to nuget.org - then let's get everything into the main branch. I just don't have time to figure out what's wrong again with this projects (WinUI, UNO), sorry.

If you want - you can develop it in a separate repository, and I'll leave a link to your repository. Because I have neither time nor desire to support WinUI/Uno implementation anyway.

**Comment by CastelloBrancoTecnologia** [comment]
OK. Created.

Please see at https://github.com/CastelloBrancoTecnologia/Material.Icons.UNO/

Feel free to say any mistakes maded by me.
